### ISSUE TITLE
"con" is not a connection error in download_jira_data.Rmd

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#146]
Hello Carlos,

While running download_jira_data.Rmd, I come across an error on this line:

https://github.com/sailuh/kaiaulu/blob/f66bc0f964861b8c928cda01c6b4b493414bf13a/vignettes/download_jira_data.Rmd#L88

Error in writeLines(json, path, useBytes = TRUE) :
'con' is not a connection

 2 . writeLines(json, path, useBytes = TRUE)
 1 . jsonlite::write_json(json_issues, save_path_issue_tracker_issues)

I double checked my filepaths and package installations, but that didn't seem to be the issue. In addition, json_issues
https://github.com/sailuh/kaiaulu/blob/f66bc0f964861b8c928cda01c6b4b493414bf13a/vignettes/download_jira_data.Rmd#L72

was not empty after running the line, so I'm confused on what could be wrong.

Relevant section of project configuration file used with download_jira_data.Rmd:

```
issue_tracker:
  jira:
    # Obtained from the project's JIRA URL
    domain: https://issues.apache.org/jira
    project_key: THRIFT
    # Download using `download_jira_data.Rmd`
    issues:
    issue_comments:
  github:
    # Obtained from the project's GitHub URL
    owner: apache
    repo: thrift
    # Download using `download_github_comments.Rmd`
    replies:
```

Also for reference I have jsonlite version 1.8.4 installed.

Thank you,
Leilani
