### ISSUE TITLE
DV8 Section for Config Files

### ISSUE THREAD

**Issue by leilani-reich** [sailuh/kaiaulu#181]
Adding a section for the DV8 functions to the existing project configuration files in the conf folder.

Follow https://github.com/sailuh/kaiaulu/issues/168#issuecomment-1475972460 for reference.

**Comment by leilani-reich** [comment]
Hi Carlos, for the DV8 config file, this would be added into each of the existing project configuration files instead of on its own, right?

Also, since we are using the folder_path for making our filenames, then in the section below, would we not want the dsmj_to_dsmb or hdsmb_sdsmb_to_hsdsmb sections?
```
tools:
  dv8:
    # the project folder path files in function calls will be used.
    # The folder name will be used in the file names.
    folder_path: ../../rawdata/dv8_thrift

    # Convert from a JSON DSM to a binary DSM.
    dsmj_to_dsmb:
      # path to JSON DSM
      dsmj_path: ''
      # path to save binary DSM
      dsmb_path: ''

    # Merge matrices in DSM (*.dv8-dsm) files to one new matrix in  (*.dv8-dsm) file
    hdsmb_sdsmb_to_hsdsmb:
      # path to the matrix from hdsmb file
      hdsmb_path: ''
      # path to the matrix from sdsmb file
      sdsm_path: ''
      # path to save the merged matrices in hsdsm.dv8-dsm file
      hsdsmb_path: ''
```

Also, are you expecting files to be saved in just the rawdata folder or should there be a dv8 subfolder, i.e. rawdata/dv8?

**Comment by carlosparadis** [comment]
Hi, 

Don't worry about this. I will figure it out based on the code I have from your DV8 functions too. Sorry, I forgot to re-assign this issue too. 

Your primary concern is 1) Finish the DV8 Cheatseet the earliest, so we can do a few quick revisions, and 2) Spend as much time as possible on those 2 Milestone 3.4 functions. My understanding is that `dependencies_to_sdsmj()` is fully working, and has no performance issues. And that `gitlog_to_hdsm()` is where all the issues currently lie (performance, file mismatch, co-change value mismatch). Moreover, there is also the abstraction request to move them to R/graph.R and R/network.R is that correct?

**Comment by leilani-reich** [comment]
Hi Carlos,
sounds good, thank you!

We will prioritize the cheatsheet. In regards to the milestone 3.4 functions,
from what I've tested, yes dependencies_to_sdsmj() is functional. Meanwhile, gitlog_to_hdsmj() has a lot of the issues you have stated. In regards to moving the functions, I added a commit on my DV8 pull request for this.

**Comment by carlosparadis** [comment]
Adding this here in case we need to refer in the future:

Originally mentioned on: https://github.com/sailuh/kaiaulu/pull/171#issuecomment-1492953371 

More specifically: 

```yaml
tool:
  # Depends allow to parse file-file static dependencies.
   dv8:
      # the project folder path files in function calls will be used. 
      # The folder name will be used in the file names.
      folder_path: ../../rawdata/dv8_thrift
      # the architectural flaws thresholds that should be used
      architectural_flaws:
         clique_depends: call,use
         crossing_cochange: 2
         .
         .
         .
         change_cover: ?            
```
